version: "3.7"
services:
  nfs:
    image: iperezx/nfs:latest
    privileged: true
    init: true
    volumes:
      - "nfs-data:/share/"
    environment:
      - "SHARED_DIRECTORY=/share/"
      - "SHARED_DIRECTORY_2=/share/nfs/client1/"
      - "SYNC=true"
    ports:
      - "2049:2049"
    network_mode: host

  pi:
    build: 
      context: .
      dockerfile: Dockerfile
    #image: iperezx/pi:latest
    privileged: true
    init: true
    volumes:
      - type: volume
        source: nfs-data
        target: /mnt/
        volume:
          nocopy: false
    command: tail -f /dev/null
    depends_on:
      - nfs
    network_mode: host

  dnsmasq:
    build: 
      context: .
      dockerfile: Dockerfile.dnsmasq
    privileged: true
    init: true
    volumes:
      - type: volume
        source: nfs-data
        target: /tftpboot
        volume:
          nocopy: true
    ports:
      - "69:69/udp"
      - "547:547/udp"
    depends_on:
      - pi
    network_mode: host

volumes:
  nfs-data: