version: "3.7"
services:
  nfs:
    image: itsthenetwork/nfs-server-alpine:latest-arm
    privileged: true
    init: true
    volumes:
      - "nfs-data:/share/"
    environment:
      - "SHARED_DIRECTORY=/share/"
      - "SYNC=true"
    ports:
      - "2049:2049"
    networks:
      pxe:
        ipv4_address: 172.18.0.2
  
  pi:
    build: 
      context: .
      dockerfile: Dockerfile
    #image: iperezx/pi:latest
    privileged: true
    init: true
    volumes:
      - type: volume
        source: nfs-data
        target: /mnt/
        volume:
          nocopy: false
    command: tail -f /dev/null
    depends_on:
      - nfs
    networks:
      pxe:
        ipv4_address: 172.18.0.4

  tftp:
    build: 
      context: .
      dockerfile: Dockerfile.tftp
    privileged: true
    init: true
    volumes:
      - type: volume
        source: nfs-data
        target: /var/tftpboot
        volume:
          nocopy: true
    ports:
      - "69:69/udp"
      - "1069:1069/udp"
      - "49152-49160/udp"
    depends_on:
      - pi
    networks:
      pxe:
        ipv4_address: 172.18.0.3

volumes:
  nfs-data:

networks:
  pxe:
    ipam:
        driver: default
        config:
          - subnet: 172.18.0.0/16